{"uuid": "ed84c6e3-d59f-4184-a00b-14b1b719240b", "children": ["561f8d72-e245-45ba-ab5f-89cc3da54e91"], "befores": [{"name": "log_on_failure", "status": "passed", "start": 1742910253940, "stop": 1742910253940}], "afters": [{"name": "log_on_failure::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=134.0.6998.118)\nStacktrace:\n\tGetHandleVerifier [0x00007FF6D9D34C25+3179557]\n\t(No symbol) [0x00007FF6D99988A0]\n\t(No symbol) [0x00007FF6D98291CA]\n\t(No symbol) [0x00007FF6D9801753]\n\t(No symbol) [0x00007FF6D98AF83E]\n\t(No symbol) [0x00007FF6D98CFBE2]\n\t(No symbol) [0x00007FF6D98A7A03]\n\t(No symbol) [0x00007FF6D98706D0]\n\t(No symbol) [0x00007FF6D9871983]\n\tGetHandleVerifier [0x00007FF6D9D967CD+3579853]\n\tGetHandleVerifier [0x00007FF6D9DAD1D2+3672530]\n\tGetHandleVerifier [0x00007FF6D9DA2153+3627347]\n\tGetHandleVerifier [0x00007FF6D9B0092A+868650]\n\t(No symbol) [0x00007FF6D99A2FFF]\n\t(No symbol) [0x00007FF6D999F4A4]\n\t(No symbol) [0x00007FF6D999F646]\n\t(No symbol) [0x00007FF6D998EAA9]\n\tBaseThreadInitThunk [0x00007FF9A1B6E8D7+23]\n\tRtlUserThreadStart [0x00007FF9A283BF6C+44]\n\n", "trace": "  File \"C:\\Users\\Admin\\PycharmProjects\\QA_FOX2\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\QA_FOX2\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\Admin\\PycharmProjects\\QA_FOX2\\tests\\conftest.py\", line 35, in log_on_failure\n    allure.attach(driver.get_screenshot_as_png(), name=\"failed_test\",\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\QA_FOX2\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1003, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\QA_FOX2\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 1013, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Admin\\PycharmProjects\\QA_FOX2\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Admin\\PycharmProjects\\QA_FOX2\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1742910258364, "stop": 1742910258414}], "start": 1742910253940, "stop": 1742910258414}